server:
  port: 9084
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev

  liquibase:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: vgdWZUy3C+x+hnW4PqQj+BtGNOo9UzdXRlRJG1U1mF8=
    expiration: 3600000
    refresh-expiration: 2592000000